### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by GuillaumeDelente**
`it was borne of a vision` -> `it was born of a vision`

Could also use

`it was born out of a vision`

### CODE REVIEW

**Review by parimalsatyal — COMMENTED** [review]
Thanks for the suggestion. Is the use of "borne" in "borne of a vision" incorrect if used in the the sense of carried by a vision (born, past of "to bear")?

**Comment by GuillaumeDelente** [comment]
Not incorrect but I think it depends what you are trying to convey.

Is the web the reason why people want to create an open system? Or is the web the result of people wanting to create an open system?

In the first case, I guess the web could "bear the vision" but I would probably use another verb, something like "support the vision"?
In the second case, I would use "born".

**Comment by markuslaker** [comment]
Born => né
Borne => porté

The child was borne out of the burning building; Github was born out of a desire to share code.

**Comment by parimalsatyal** [comment]
Ah, thanks for the clarification! In this case then, I agree that "born" (né) would indeed be the better option. Merci.

**Pull request merged**
